### ISSUE TITLE
Machinery option "-i" isn't handled correctly

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1185]
The option -i will take everything that's followed as value - e.g. -ip will not report "invalid argument", but "p" would end up as IP address.

´# machinery show --html -incredible localhost´
There is a web server running, serving the description on http://ncredible:7586/localhost.
((Web server will _not_ run))

´# machinery show --html -i=10.160.66.80 localhost´
There is a web server running, serving the description on http://=10.160.66.80:7586/localhost.
((Web server will _not_ run))

´# machinery show --html -i 10.160.66.80 localhost´
There is a web server running, serving the description on http://10.160.66.80:7586/localhost.
((Web server will run O.K.))

´# machinery show --html --ip 10.160.66.80 localhost´
There is a web server running, serving the description on http://10.160.66.80:7586/localhost.
((Web server will run O.K.))

´# machinery show --html --ip=10.160.66.80 localhost´
There is a web server running, serving the description on http://10.160.66.80:7586/localhost.
((Web server will run O.K.))

**Comment by mschnitzer** [comment]
WIP

**Comment by mschnitzer** [comment]
The commands which you executed are all valid.

For example in `git`:
`git commit myfile.txt -mtest` -> The commit message would be `test`
`git commit myfile.txt -m=test` -> The commit message would be `=test`

Many programs accept those arguments.

**Comment by svollath** [comment]
What I had in mind, is input checking - so check if "-i" is followed by an ip address (ipv4/6?). There's no need to do a "try starting" statement and make 'getaddrinfo' fail for e.g. "p" - even if you then return a sane error.

**Comment by cornelius** [comment]
I don't think we should do a lot more checking on the value of the option. There are actually only a few valid values, the ones which result in an IP address of the host machinery is running on. Proper error reporting from trying to start the server will give somewhat reasonable error messages, so the user has a chance to understand what is going on.

I do think we need to improve the documentation, so that it's clearer what this option does and what are valid values.

Long-term we should rethink if this option is actually the right way to handle things, because it is not very convenient to use and it only addresses one little part of the use case of serving descriptions to other users. We haven't really addressed this use case, so having the option at all is premature.

**Comment by mschnitzer** [comment]
Fixed in https://github.com/SUSE/machinery/commit/79565a8c1285882b9de1b4ba5523edeb36c10773
