### ISSUE TITLE
HTML view doesn't show content of directories which names contain special charakters

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1549]
In order to test issue#1497 I created four unmanaged files, while two of them are in directories which also contain special characters in their name:
/test:test
/test%test
/te:st/test:test1
/te%st/test%test1

While the directories seem to be inspected correctly (description/unmanaged_files/trees):
'# tar -tzf te%st.tgz' 
te%st/
te%st/test%test1

... HTML view will only show the directories, but not their content:
/te%st/ (dir)
/te:st/ (dir)
/test%test (file)
/test:test (file)

So files "test:test1" and "test%test1" within are not shown.

**Comment by greygoo** [comment]
This is the intended behaviour and not introduced by the changes. Currently the html view only shows the content of unmanaged files that are located within managed directories. Unmanaged directories and their content however are packaged and extracted but their content is not accessible in the html view. I admit that this can feel confusing as I ran into the same situation and also assumed it to be a bug, we should consider changing that behaviour. 
It is however, not related to the P7 card in which context this issue was filed.
