### ISSUE TITLE
Unsupported Platform: SUSE Linux Enterprise Desktop 12

### ISSUE THREAD

**Issue by metti** [SUSE/machinery#1638]
Most likely the Desktop distribution has the same support level as the Server distribution ... and there is a small typo in Officially :-)

% cat /etc/os-release                 
NAME="SLED"
VERSION="12"
VERSION_ID="12"
PRETTY_NAME="SUSE Linux Enterprise Desktop 12"
ID="sled"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sled:12"

 % machinery serve --help  
You are running Machinery on a platform we do not explicitly support and test.
It still could work very well. If you run into issues or would like to provide us feedback, you are welcome to file an issue at https://github.com/SUSE/machinery/issues/new or write an email to machinery@lists.suse.com.
Oficially supported operating systems are: 'SUSE Linux Enterprise Server 12, openSUSE 13.1 (Bottle), openSUSE 13.2 (Harlequin), openSUSE Leap, openSUSE Tumbleweed'

**Comment by mauromorales** [comment]
@metti thanks for reporting it ... We'll work on the fixes and get back to you.

**Comment by mauromorales** [comment]
@metti @fcrozat I've merged a fix for this, if you are testing from upstream please try it out otherwise packages should be updated in the next few weeks. I'll close this for now but if you find anything we can re open the issue.

Sorry it took some time but I wanted to make more open how we allow machinery to run on other systems in general and I've removed the notion of "supported" to allow any system that has the required tools in place to just run. This the only reason we didn't merge @fcrozat 's PR (but thanks a lot for submitting, hope to see some other PRs coming in :wink:)

**Comment by mauromorales** [comment]
relates to #1693
