### ISSUE TITLE
Allow password authentication + sudo password declaration 

### ISSUE THREAD

**Issue by darksheer** [SUSE/machinery#2013]
Would like to see the ability to connect to remote machines via password and be able to declare the sudo password for privilege escalation.

**Comment by mauromorales** [comment]
Hi @darksheer and thanks for opening this issue

Regarding the password authentication by design we decided to only use ssh key access because its secure and easy to automate. Let me ask you, why isn't ssh key access good for you?

For the sudo privilege escalation this would just add unnecessary complexity because the scopes inspect areas that require sudo access any way. Here you can simply use the `--remote-user` option to give a different user than root that has sudo permissions.

I'm closing the issue for now but please keep the conversation so we can see in which way machinery can work best for you :) and of course we can reopen if we see it necessary.
