### ISSUE TITLE
1 click installer for Leap doesn't install the latest available for Leap

### ISSUE THREAD

**Issue by mauromorales** [SUSE/machinery#2159]
When installing Machinery using the 1 click installer from the website it installs version 1.14 instead of the latest (1.18 ATM)

**Comment by thardeck** [comment]
It was a user issue besides the non-intuitive design of the installer.

The problem was that a repository was selected which uses not the update repository but the original one.

If you do not click on any checkbox machinery is installed from the update channel.

We decided in the past that we do not want to add extra repositories if machinery is part of the distribution, that's why Tumbleweed and Leap do not get our build service repo.
