### ISSUE TITLE
Docs fix: EL6/7 installation docs will not work

### ISSUE THREAD

**Issue by howardjones** [SUSE/machinery#2259]
If you install ruby from yum, and then rake from gems, rake complains that it requires ruby 2.2, which is not what you'll get from yum (2.0.0). To use with the gem-installed rake, you actually need to mess around with Software Collections to get Ruby 2.2. 

I'm not a ruby person, but I guess there might be an older version of rake than keeps both machinery and ruby 2.0 happy?

**Comment by thardeck** [comment]
Yes, there should be a combination but since even [Ruby 2.2](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/) is not supported anymore I suppose it is not worth the effort to find it.

Especially since you would have to make sure for each gem that you do not prevent security fixes from being applied  by limiting certain versions.

**Comment by howardjones** [comment]
Then the bug is that this page is incorrect :-)

https://github.com/SUSE/machinery/wiki/Installation-on-Other-Distributions
