### ISSUE TITLE
Specifying --html does not open Firefox in Tumbleweed

### ISSUE THREAD

**Issue by boblmartens** [SUSE/machinery#884]
Hi, me again.

After inspecting my local system with `machinery inspect localhost` I attempt to show the html view with `machinery show --html localhost` and I don't get anything.

This is with the latest Tumbleweed snapshot as of May 11, 2015.

**Comment by cornelius** [comment]
Does `machinery show localhost` show something?

**Comment by boblmartens** [comment]
Yes it does, it shows the description of my local machine.

**Comment by cornelius** [comment]
I suppose this is related to requiring root rights to do the inspection of localhost. That means that the description is stored in the home directory of the root user and you need to be root to read it. With the `--html` option `xdg-open` is called to run the browser, which probably fails because it doesn't have sufficient privileges to show the browser window on the users desktop.

The HTML is stored in the description, you can manually open it by going to `~/.machinery/localhost/index.html`.

Another way would be to not directly inspect `localhost`, but use ssh to log in to your local host by using its external host name. Then machinery doesn't need to run as root and the data is stored and is accessible in your normal users's home directory.

**Comment by boblmartens** [comment]
Yup, that did it ... was fairly certain it was an issue on my end.

Thanks!

**Comment by cornelius** [comment]
OK, great. I'll close this issue then.
